name: CI/CD
on: [push]
env:
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_PAGOSB }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_PAGOSB }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PAGOSB }}
jobs:
    Build:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/modulo_pagosB'
        steps:
            - uses: actions/checkout@v4
            - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
            - name: "use node ${{ env.node_version }}"
              uses: actions/setup-node@v3
              with:
                node-version: "${{ env.node_version }}"
            - name: Install Dependencies
              run: yarn install
            - name: Build
              run: yarn build

    VercelDeploy:
        needs: Build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/modulo_pagosB'
        steps:
            - uses: actions/checkout@v4
            - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
            - name: "use node ${{ env.node_version }}"
              uses: actions/setup-node@v3
              with:
                node-version: "${{ env.node_version }}"
            
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Configure Vercel
              run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN_PAGOSB }}
            - name: Trigger Vercel deployment
              run: vercel deploy --no-wait --token=${{ secrets.VERCEL_TOKEN_PAGOSB }}

    SonarQubeAnalysis:
      needs: Build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/modulo_pagosB'
      steps:
          - uses: actions/checkout@v4
          - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
          - name: "use node ${{ env.node_version }}"
            uses: actions/setup-node@v3
            with:
              node-version: "${{ env.node_version }}"
          - name: SonarCloud Scan
            uses: sonarsource/sonarcloud-github-action@master
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_PAGOSB }}
      
    